[package]
name = "rust-elf"
version = "0.1.0"
authors = ["Adam Stepan <adam.stepan@firma.seznam.cz>"]
edition = "2018"
keywords = ["readelf", "elf"]

[dependencies]
byteorder = { version = "1" }
clap = { version = "2" }
